"""
skills/generate_dto/skill.py
Generates a plain Java DTO (Data Transfer Object) class — no JPA, no @Entity.
Placed under the module's .dto package.

Reuses the same inline template logic as generate_entity but:
- package is <base_package>.dto  (not .entity)
- No JPA annotations ever
- Idempotent: returns already_exists if the DTO FQN is already in the context
  (stored under a "dto:<fqn>" key in the kv table to avoid polluting entity table)
"""

from __future__ import annotations

from pathlib import Path

from project_context import ProjectContext
from tools.template_engine import get_engine
import logging

logger = logging.getLogger(__name__)

DTO_TEMPLATE = """\
package {{ package }};

import java.io.Serializable;
{% for imp in imports %}
import {{ imp }};
{% endfor %}

/**
 * DTO: {{ class_name }}
 * Auto-generated by crewai-microservice-builder
 */
public class {{ class_name }} implements Serializable {

    private static final long serialVersionUID = 1L;

{% for field in fields %}
    private {{ field.type }} {{ field.name }};
{% endfor %}

    // Constructors
    public {{ class_name }}() {}

    // Getters and Setters
{% for field in fields %}
    public {{ field.type }} get{{ field.name | capitalize }}() {
        return {{ field.name }};
    }

    public void set{{ field.name | capitalize }}({{ field.type }} {{ field.name }}) {
        this.{{ field.name }} = {{ field.name }};
    }

{% endfor %}
    @Override
    public String toString() {
        return "{{ class_name }}{" +
{% for field in fields %}
            "{{ field.name }}='" + {{ field.name }} + "'"{% if not loop.last %} + ", " +{% else %} +{% endif %}

{% endfor %}
            "}";
    }
}
"""

_TYPE_IMPORT_MAP = {
    "LocalDate": "java.time.LocalDate",
    "LocalDateTime": "java.time.LocalDateTime",
    "BigDecimal": "java.math.BigDecimal",
    "List": "java.util.List",
    "Map": "java.util.Map",
    "Set": "java.util.Set",
}


def _normalize_fields(raw: list) -> list[dict]:
    result = []
    for f in raw:
        if isinstance(f, str):
            result.append({"name": f.strip(), "type": "String"})
        elif isinstance(f, dict):
            result.append({
                "name": f.get("name", "field"),
                "type": f.get("type", "String"),
            })
    return result


def _collect_imports(fields: list) -> list[str]:
    needed = set()
    for f in fields:
        t = f.get("type", "")
        for k, v in _TYPE_IMPORT_MAP.items():
            if k in t:
                needed.add(v)
    return sorted(needed)


def run(params: dict, context: ProjectContext) -> dict:
    module_name: str = params.get("module_name", "")
    if not module_name:
        return {"status": "error", "message": "Missing required param: module_name"}

    class_name: str = (
        params.get("class_name")
        or params.get("dto_name")
        or params.get("name")
        or ""
    )
    if not class_name:
        return {"status": "error", "message": "Missing required param: class_name (e.g. 'UserDto')"}

    module_info = context.modules.get(module_name)
    if not module_info:
        return {"status": "error", "message": f"Module '{module_name}' not found."}

    base_package = module_info.base_package
    dto_package = base_package + ".dto"
    fqn = f"{dto_package}.{class_name}"

    # Idempotency check via kv store (avoids polluting entity table)
    kv_key = f"dto:{fqn}"
    if context.get_kv(kv_key):
        logger.info(f"DTO '{fqn}' already exists, skipping")
        return {
            "status": "already_exists",
            "fqn": fqn,
            "message": f"DTO '{class_name}' already exists.",
        }

    fields = _normalize_fields(params.get("fields", []))
    imports = _collect_imports(fields)

    module_path = context.module_path(module_name)
    src_root = module_path / "src" / "main" / "java"
    dto_dir = src_root / Path(*dto_package.split("."))
    dto_dir.mkdir(parents=True, exist_ok=True)

    out_path = dto_dir / f"{class_name}.java"
    if out_path.exists() and not params.get("overwrite", False):
        context.set_kv(kv_key, fqn)
        return {
            "status": "already_exists",
            "fqn": fqn,
            "file": str(out_path),
            "message": f"DTO file '{class_name}.java' already exists.",
        }

    engine = get_engine()
    content = engine.render_string(DTO_TEMPLATE, {
        "package": dto_package,
        "class_name": class_name,
        "fields": fields,
        "imports": imports,
    })
    out_path.write_text(content, encoding="utf-8")
    logger.info(f"Written DTO: {out_path}")

    context.set_kv(kv_key, fqn)
    context.log_change(
        module_name=module_name,
        file_path=str(out_path.relative_to(module_path)),
        change_type="create",
        description=f"Generated DTO '{class_name}' with {len(fields)} fields",
    )

    return {
        "status": "success",
        "file": str(out_path),
        "fqn": fqn,
        "dto_package": dto_package,
    }