"""
skills/generate_entity/skill.py
Generates a JPA/plain Java entity class.

Fix (v2):
- class_name 兼容 LLM 可能传的 entity_name / name 键名
- fields 防御性归一化：字符串字段 → {name, type, annotations:[]}
- 幂等检查：entity FQN 已存在时返回 already_exists
- 记录 change_history
"""

from __future__ import annotations

from pathlib import Path

from project_context import EntityInfo, ProjectContext
from tools.template_engine import get_engine
import logging

logger = logging.getLogger(__name__)

ENTITY_TEMPLATE = """\
package {{ package }};

import java.io.Serializable;
{% for imp in imports %}
import {{ imp }};
{% endfor %}
{% if use_jpa %}
import javax.persistence.*;
{% endif %}

/**
 * Entity: {{ class_name }}
 * Auto-generated by crewai-microservice-builder
 */
{% if use_jpa %}
@Entity
@Table(name = "{{ table_name }}")
{% endif %}
public class {{ class_name }} implements Serializable {

    private static final long serialVersionUID = 1L;

{% if use_jpa %}
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
{% endif %}
    private Long id;

{% for field in fields %}
{% for ann in field.annotations %}
    {{ ann }}
{% endfor %}
    private {{ field.type }} {{ field.name }};

{% endfor %}
    // Constructors
    public {{ class_name }}() {}

    // Getters and Setters
    public Long getId() { return id; }
    public void setId(Long id) { this.id = id; }

{% for field in fields %}
    public {{ field.type }} get{{ field.name | capitalize }}() {
        return {{ field.name }};
    }

    public void set{{ field.name | capitalize }}({{ field.type }} {{ field.name }}) {
        this.{{ field.name }} = {{ field.name }};
    }

{% endfor %}
    @Override
    public String toString() {
        return "{{ class_name }}{" +
            "id=" + id +
{% for field in fields %}
            ", {{ field.name }}='" + {{ field.name }} + "'" +
{% endfor %}
            "}";
    }
}
"""


def _resolve_class_name(params: dict) -> str | None:
    """
    LLM 可能用不同键名传实体类名，按优先级尝试：
    class_name → entity_name → name → entity_class
    """
    for key in ("class_name", "entity_name", "name", "entity_class"):
        val = params.get(key)
        if val and isinstance(val, str) and val.strip():
            return val.strip()
    return None


def _normalize_fields(raw: list) -> list[dict]:
    """
    规范化 fields 列表：
    - str → {name: str, type: "String", annotations: []}
    - dict → 补全缺失字段
    - 过滤掉名为 'id' 的字段：模板已硬编码 private Long id + getId()/setId()，
      LLM 若把 id 也放进 fields 会导致重复声明和类型冲突
    """
    result = []
    for f in raw:
        if isinstance(f, str):
            name = f.strip()
            if name == "id":
                logger.info("generate_entity: skipping 'id' field (already generated by template)")
                continue
            result.append({"name": name, "type": "String", "annotations": []})
        elif isinstance(f, dict):
            name = f.get("name", "field")
            if name == "id":
                logger.info("generate_entity: skipping 'id' field (already generated by template)")
                continue
            result.append({
                "name": name,
                "type": f.get("type", "String"),
                "annotations": f.get("annotations") or [],
            })
        else:
            logger.warning(f"generate_entity: unexpected field format, skipping: {f!r}")
    return result


def run(params: dict, context: ProjectContext) -> dict:
    module_name: str = params.get("module_name", "")
    if not module_name:
        return {"status": "error", "message": "Missing required param: module_name"}

    # ── 兼容多种键名 ──
    class_name = _resolve_class_name(params)
    if not class_name:
        return {
            "status": "error",
            "message": (
                "Missing required param: class_name (also tried entity_name, name, entity_class). "
                "Please re-call with class_name='YourEntityName'."
            ),
        }

    fields: list = _normalize_fields(params.get("fields", []))
    use_jpa: bool = bool(params.get("use_jpa", False))
    table_name: str = params.get("table_name", class_name.lower() + "s")

    module_info = context.modules.get(module_name)
    if not module_info:
        return {"status": "error", "message": f"Module '{module_name}' not found."}

    base_package = module_info.base_package
    entity_package = base_package + ".entity"
    fqn = f"{entity_package}.{class_name}"

    # ── 幂等检查 ──
    if context.entity_exists(fqn):
        logger.info(f"Entity '{fqn}' already exists, skipping")
        return {
            "status": "already_exists",
            "fqn": fqn,
            "message": f"Entity '{class_name}' already exists. Use incremental_modify to add fields.",
        }

    module_path = context.module_path(module_name)
    src_root = module_path / "src" / "main" / "java"
    entity_dir = src_root / Path(*entity_package.split("."))
    entity_dir.mkdir(parents=True, exist_ok=True)

    imports = _collect_imports(fields)

    engine = get_engine()
    ctx = {
        "package": entity_package,
        "class_name": class_name,
        "fields": fields,
        "use_jpa": use_jpa,
        "table_name": table_name,
        "imports": imports,
    }

    content = engine.render_string(ENTITY_TEMPLATE, ctx)
    out_path = entity_dir / f"{class_name}.java"
    out_path.write_text(content, encoding="utf-8")
    logger.info(f"Written entity: {out_path}")

    info = EntityInfo(module_name=module_name, fqn=fqn, fields=fields)
    context.save_entity(info)

    context.log_change(
        module_name=module_name,
        file_path=str(out_path.relative_to(module_path)),
        change_type="create",
        description=f"Generated entity '{class_name}' with {len(fields)} fields, jpa={use_jpa}",
    )

    return {
        "status": "success",
        "file": str(out_path),
        "fqn": fqn,
    }


def _collect_imports(fields: list) -> list[str]:
    type_map = {
        "LocalDate": "java.time.LocalDate",
        "LocalDateTime": "java.time.LocalDateTime",
        "BigDecimal": "java.math.BigDecimal",
        "List": "java.util.List",
        "Map": "java.util.Map",
        "Set": "java.util.Set",
    }
    needed = set()
    for f in fields:
        t = f.get("type", "")
        for k, v in type_map.items():
            if k in t:
                needed.add(v)
    return sorted(needed)